### ISSUE TITLE
Правки по ЛР 1

### ISSUE THREAD

**Issue by BakasaRus** [pimushkin/weather-forecast-web-project#1]
Перед сдачей нужно поправить эти косяки:

- `header` вынести из `main`;
- сделать отступ сверху у кнопки "Обновить геолокацию";
- в `main` поменять дочерние `div` на `section`;
- убрать `h3` у температуры в карточке;
- сделать температуру и иконку рядом с названием города на любых разрешениях;
![Screenshot_20210318_151652](https://user-images.githubusercontent.com/21131366/111624639-ff51ee80-87fc-11eb-97da-d60cb385dee5.png)
- убрать лишние `div` (например, в части с добавлением города заголовок зачем-то обёрнут в `div`);
- вместо класса `info-line` на всех элементах списка сделать класс для всего списка и применять стиль к элементам, исходя из класса всего списка; другой вариант - избавиться от обёртки `div` и вешать класс на сам список;
- Все стили перенести в классы.

На защите могу найти ещё косяки :)

**Comment by pimushkin** [comment]
@BakasaRus добавил класс для `ul` и через селектор применил стили к `li`, убрал div поверх списка в избранном(e8096da653244f290216557e52b181f433a593bb)
